engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  eslint:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseClassName:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.php"